import { Employee } from "@/types/employee";

export const mockEmployees: Employee[] = [
    {
        _id: "1",
        codigo: "EMP001",
        tipoDocumento: "CC",
        documento: "1020304050",
        nombre: "Juan Felipe",
        apellidos: "Alzate",
        nombreCompleto: "Juan Felipe Alzate",
        correo: "juan@colegio.edu.co",
        telefono: "3000000001",
        cargo: "Soporte TI",
        dependencia: "Tecnología",
        tipoContrato: "Indefinido",
        horario: "ADMINISTRATIVOS",
        biometrico: "1001",
        estado: "ACTIVO",
        fechaIngreso: new Date("2024-01-10"),
        observaciones: ""
    },
    {
        _id: "2",
        codigo: "EMP002",
        tipoDocumento: "CC",
        documento: "1000000001",
        nombre: "Angie",
        apellidos: "Cárdenas",
        nombreCompleto: "Angie Cárdenas",
        correo: "angie@colegio.edu.co",
        telefono: "3000000002",
        cargo: "Administrativa",
        dependencia: "Administración",
        tipoContrato: "Fijo",
        horario: "ADMINISTRATIVOS",
        biometrico: "1002",
        estado: "ACTIVO",
        fechaIngreso: new Date("2023-08-15"),
        observaciones: ""
    },
    {
        _id: "3",
        codigo: "EMP003",
        tipoDocumento: "CC",
        documento: "1000000002",
        nombre: "Carlos",
        apellidos: "Pérez",
        nombreCompleto: "Carlos Pérez",
        correo: "carlos@colegio.edu.co",
        telefono: "3000000003",
        cargo: "Docente",
        dependencia: "Primaria",
        tipoContrato: "Indefinido",
        horario: "DOCENTES",
        biometrico: "1003",
        estado: "ACTIVO",
        fechaIngreso: new Date("2022-02-01"),
        observaciones: ""
    },
    {
        _id: "4",
        codigo: "EMP004",
        tipoDocumento: "CC",
        documento: "1000000003",
        nombre: "Laura",
        apellidos: "Gómez",
        nombreCompleto: "Laura Gómez",
        correo: "laura@colegio.edu.co",
        telefono: "3000000004",
        cargo: "Servicios Generales",
        dependencia: "Mantenimiento",
        tipoContrato: "Fijo",
        horario: "SERVICIOS",
        biometrico: "1004",
        estado: "ACTIVO",
        fechaIngreso: new Date("2024-03-05"),
        observaciones: ""
    },
    {
        _id: "5",
        codigo: "EMP005",
        tipoDocumento: "CC",
        documento: "1000000004",
        nombre: "Pedro",
        apellidos: "Rodríguez",
        nombreCompleto: "Pedro Rodríguez",
        correo: "pedro@colegio.edu.co",
        telefono: "3000000005",
        cargo: "Coordinador",
        dependencia: "Académica",
        tipoContrato: "Indefinido",
        horario: "DIRECTIVAS",
        biometrico: "1005",
        estado: "INACTIVO",
        fechaIngreso: new Date("2021-01-20"),
        observaciones: ""
    }
];